
version: '3.8'
services:
  mysqldb:
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=zeus
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306  
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=zeus
volumes:
  db: